
image: java:8-jdk

stages:
  - build
  - test
  - publish

variables:
  OSSHR_SECRETS: "-PossrhUsername=$ossrhUsername -PossrhPassword=$ossrhPassword"

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  script:
    - ./gradlew check

publish:
  stage: publish
  script:
    - ./gradlew publish $OSSHR_SECRETS
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master
