dist: xenial
language: java
jdk:
  - openjdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
install: "./gradlew assemble"
script:
  - "./gradlew check"
after_success:
  - "./gradlew dokka"
  - "./gradlew publish -PossrhUsername=$ossrhUsername -PossrhPassword=$ossrhPassword"
deploy:
  provider: pages
  local-dir: build/html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
